name: bump-version-pr

on:
  workflow_dispatch:
    inputs:
      pr-assignees:
        description: ""
        required: false
        default: ""
      pr-reviewers:
        description: ""
        required: false
        default: ""

jobs:
  bump-version-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ inputs.token }}

      - name: Install dependencies
        run: sudo apt-get install -y python3-catkin-tools
        shell: bash

      - name: Bump version from humble branch
        id: bump-version-from-humble-branch
        run: |
          git fetch origin --tags
          git checkout origin/humble
          git checkout -b tmp/chore/bump_version_base
          git fetch origin main
          git merge origin/main
          catkin_generate_changelog -y
          git add *
          git commit -m "update CHANGELOG.rst"
          catkin_prepare_release -y --bump minor --no-push
          version=$(git describe --tags)
          echo '::set-output name=version::${version}'
        shell: bash

      - name: Create target branch
        run: |
          git checkout origin/main
          git checkout -b tmp/chore/bump_version
          git merge tmp/chore/bump_version_base
          git push origin tmp/chore/bump_version_base
        shell: bash

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ inputs.token }}
          base: main
          branch: tmp/chore/bump_version
          title: "Bump version to ${{ steps.bump-version-from-humble-branch.outputs.version }}"
          body: "Bump version to ${{ steps.bump-version-from-humble-branch.outputs.version }}"
          assignees: ${{ inputs.pr-assignees }}
          reviewers: ${{ inputs.pr-reviewers }}
          author: github-actions <github-actions@github.com>
          signoff: true
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
        shell: bash
